######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 15 17:01:48 2011
######################################################################

include(dissent.pro)
TEMPLATE = app
TARGET = lrs

SOURCES += src/Applications/LRSMain.cpp
