######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 15 17:01:48 2011
######################################################################

TARGET = lrs
DEPENDPATH += 
CONFIG += qt debug
QT = core network
DEFINES += "VERSION=3"
QMAKE_CXXFLAGS += -Werror
QMAKE_CFLAGS += -Werror

# Input
LIBS += -lcryptopp 

HEADERS += src/SigmaProtocol.hpp

SOURCES += src/main.cpp
