######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 15 17:01:48 2011
######################################################################

TARGET = pbcparams
DEPENDPATH += 
CONFIG += qt debug
QT = core network
DEFINES += "VERSION=3"
QMAKE_CXXFLAGS += -Werror 
QMAKE_CFLAGS += -Werror 
LIBS += -lpbc -lgmp

# Input

SOURCES += main.cpp
